name: deepfakes-env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.6.9
  - pip=20.0.2
  - pytorch==1.4.0
  - torchvision=0.5.0
  - pip:
    - matplotlib==3.2.1
    - PyYAML==3.13
    - tqdm==4.38.0
    - imageio==2.4.1
    - scikit-image==0.16.2
    - scikit-learn==0.22.2.post1
    - pandas==1.0.3
    - Pillow==7.0.0